# ligatures are not possible in alacritty (->, =>, etc)
[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}

[colors]
primary.background = "#000000"

[window]
opacity = 0.8
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
