[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[colors.primary]
background = "#000000"

[window]
opacity = 0.6

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
